[workspace]
authors = ["yhori <y.hori@syntheticgestalt.com>"]
channels = ["conda-forge"]
name = "aws-marketplace-sg4d100m"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
notebook = ">=7.4.3,<8"
sagemaker = ">=2.198.0,<3"
python = "3.11.*"
polars = ">=1.30.0,<2"

[feature.dev.dependencies]
ipykernel = "*"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
